version: "3"
services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./volumes/db:/var/lib/postgresql/data
    networks:
      - mynetwork

  backend:
    container_name: backend
    image: spyspoisspuis/senior-course-backend:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DB_HOST: db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
